### ISSUE TITLE
hospital-coordinates for frontend

### ISSUE THREAD

**Issue by nfroidevaux** [eonum/geopitalsuisse#26]
1. Hospital coordinates in decimal numbers for frontend
2. Check coordinates (some hospitals are out of Switzerland)

**Comment by manuelaeschler** [comment]
Checked coordinates out of switzerland: incorrect/ unrecognized address
Taminaplatz 1, 7317 Valens - Coordinates in USA or not recognized
Google Maps finds the correct place, assuming using additional informations as users location.
Solutions:
- Change to correct address (the address will be incorrect in hospital profile)
- Change coordinates afterwards manually (recomended)
