### ISSUE TITLE
Alle Standorte anzeigen.

### ISSUE THREAD

**Issue by aurorra** [eonum/geopitalsuisse#38]
Backend: Upload für das neue Datenformat Datensätze vor 2015 sind weniger interessant, warten auf Rückmeldung von Tim, ob diese auch hochgeladen werden sollen

Frontend: neue Checkbox wird hinzugefügt mit Hinweis, bei anklicken werden alle Standorte angezeigt (nicht-Hauptstandorte mit Faktor 1/6 anzeigen)

**Comment by nfroidevaux** [comment]
removed from requirements
