### ISSUE TITLE
Map implementieren

### ISSUE THREAD

**Issue by nfroidevaux** [eonum/geopitalsuisse#4]

**Comment by nfroidevaux** [comment]
Angular Google Maps not usable, new Frontend-Architecture needed with
- Open Street Map
- Open Layer for visualization options
- SVG Layer for d3-visualization options (extension)

**Comment by nfroidevaux** [comment]
Open Street Map implemented
Open Layer implemented
SVG Layer for 3d-visualization implemented
Design with Mapbox applied
-> to be refactored into angular architecture

**Comment by aurorra** [comment]
Everything implemented, but code cleanup needed.
