### ISSUE TITLE
Scatterplot with best-fit

### ISSUE THREAD

**Issue by tschimbr** [eonum/geopitalsuisse#62]
In a different view (switch between map and statistics view in the upper left corner) we should display a scatterplot of all hospitals with a best-fit line.
 - select x-cordinate field (number)
 - select y-coordinate field (number)
 - optionally select color identifier field (categorical field)
 - best fit line
 - filter hospitals (same filter as in the map view)

**Comment by doutzi** [comment]
Done in #71
