### ISSUE TITLE
refactor JSON API

### ISSUE THREAD

**Issue by tschimbr** [eonum/geopitalsuisse#74]
Ein Hospital-Model: Name, Adresse, Ort, Latitude, Longitude, Typ, Attribute{}
Später evtl. die Möglichkeit, einige Attribute nur lazy hineinzuladen. Sobald die Datenmenge zu gross wird, um immer zu laden.
```
{ 
name: string, 
address: string,
location: string,
latitude: string, 
longitude: string, 
typ: Typ, 
attributes: Attribute{ code: { value: value, years: { 2012: value, 2013: value }}}
}
```

Ein Attribut-Model: Code, Kategorie, Name_de, Name_fr, Name_it, Wert, Jahr

See: https://github.com/eonum/casematch/blob/master/app/models/variable.rb
```

{ 
code: string, 
type: # categorical, numerical, string
values: # possible values if categorical
values_de,
values_fr,
values_it,
categories: array of strings, # semantics
name_de: string,
name_fr: string, 
name_it: string, 
}
```

**Comment by tschimbr** [comment]
Implement this in https://github.com/eonum/qualimed-hospitals

**Comment by doutzi** [comment]
Solved by #79
